import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import LayoutApp from './App';
import HelloWorld from './App';
import WelcomeApp from './App';
import ClockApp from './App';
import CounterApp from './App';
import Toggle from './App';
import GreetingApp from './App';
import MailBoxApp from './App';
import Page from './App';
import Container from './App';
import BlogApp from './App';
import NameForm from './App';
import EssayForm from './App';
import FlavorForm from './App';
import registerServiceWorker from './registerServiceWorker';

// ReactDOM.render(<App />, document.getElementById('root'));
// ReactDOM.render(<LayoutApp />, document.getElementById('root'));
// ReactDOM.render(<HelloWorld />, document.getElementById('root'));
// ReactDOM.render(<WelcomeApp />, document.getElementById('root'));
// ReactDOM.render(<ClockApp />, document.getElementById('root'));
// ReactDOM.render(<CounterApp />, document.getElementById('root'));
// ReactDOM.render(<Toggle />, document.getElementById('root'));
// ReactDOM.render(<GreetingApp />, document.getElementById('root'));
// ReactDOM.render(<MailBoxApp />, document.getElementById('root'));
// ReactDOM.render(<Page />, document.getElementById('root'));
// ReactDOM.render(<Container />, document.getElementById('root'));
// ReactDOM.render(<BlogApp />, document.getElementById('root'));
// ReactDOM.render(<NameForm />, document.getElementById('root'));
// ReactDOM.render(<EssayForm />, document.getElementById('root'));
ReactDOM.render(<FlavorForm />, document.getElementById('root'));
